### ISSUE TITLE
in 2016, the font format stack shown no longer makes sense.

### ISSUE THREAD

**Issue by Pomax** [dwighthouse/onfontready#5]
The stack shown in https://github.com/dwighthouse/onfontready/blob/master/README.md#usage doesn't make sense anymore in mid-2016, with Microsoft having disavowed IE8 and below, and Safari and Android having great webfont support by now. 

Long story short: http://stackoverflow.com/questions/36105194/are-eot-ttf-and-svg-still-necessary-in-the-font-face-declaration/36110385#36110385

Showing this stack should come with either an explicit warning that this is _not_ modern CSS anymore (just WOFF and WOFF2 means your webfonts work on every currently-supported browser), or it should show a modern syntax with only woff/woff2 with a link to an ancient.css file that shows the format we needed three years ago =)

(although even then, SVG fonts were _never_ useful, and we killed off the spec as soon as it turned out they were in fact a terrible idea, which is why most current browsers did support SVG at some point, but have _removed_ SVG font support again. It's a revoked spec).

**Comment by dwighthouse** [comment]
Thanks for the feedback. I will make this information available when I update the documentation with usage examples. Keep in mind that this library is designed to work even back to IE6 (for the lolz), so having obsolete font formats should come as no surprise. Nevertheless, SVG fonts may not be legitimate for any time period. I will look into it further.

**Comment by dwighthouse** [comment]
To be clear, I plan to go into more depth with which font format specs to apply depending on which version of the library is used (modern vs legacy).

**Comment by Pomax** [comment]
I'm not sure I see the value in making sure versions of IE are supported that Microsoft themselves no longer officially support. IE8 and below have been abandoned, much like how IE4 and 5 were abandoned, we just (finally) moved on to a new "minimum IE version". As of January 12th 2016, Microsoft disavowed IE8 and below, and only supports IE9 *very specifically* **only** on Vista SP2. IE9 on Windows 7, for instance, is *not* supported, so questions need to be asked why one would keep pretending these incredibly insecure browsers should still be catered for. Surely, we're not telling people who still use them that they're perfectly safe on the web - their operating systems and browsers are so full of holes they might as well publically post their personally identifiable information and financial details.

**Comment by dwighthouse** [comment]
Yeah, I normally would agree with you. My forward looking projects are not directly supporting browsers IE9 and below. There are a couple of things to consider for such a generic library as `onfontready` though:

IE6/7/8 is still somewhere around 6% worldwide summed usage. IE9+ make up as much as 10% on some measures. While Microsoft may have disavowed these browsers, they are still in major use in some parts of the world. It is well outside of the scope of `onfontready` to tell users what browser they should be using. No doubt, anyone using those versions has probably been told exactly what browsers they should be using for over five years. The fact that they are still using them implies that they have no choice in the matter.

Effectively, the `legacy` version of `onfontready` exists to make the claim that "`onfontready` supports ALL browsers." To my knowledge it does. I know of no browser capable of custom fonts that won't also support the `legacy` version of my library. If I had the capacity to test IE4 and 5, I would. This part of the library is mostly a personal challenge. I didn't have to make it work in older browsers. I didn't have to make it this small either.

**Comment by Pomax** [comment]
fair points.

**Comment by dwighthouse** [comment]
Let's keep this issue open until I have a chance to re-evaluate the stacks and remove unnecessary font types when I add new documentation.

@Pomax I was wondering, could you supply me with a binary copy of your [special font](http://processingjs.nihongoresources.com/the_smallest_font/) as a TTF file? In addition, can you provide some variation of it (a font containing only the the 'A' character, no spaces) in an EOT format as well so I can test older IEs? I'd convert it myself, but I know FontSquirrel will add a space automatically.

**Comment by Pomax** [comment]
That's actually something you don't need me for, the browsr can already do that for you: open dev tools, go to the network tab, and simply open the ont's data-uri in a new tab. Now it's a download =)

As for variants at that small a size, we're talking non-trivial changes, which require more time that I have available for the forseeable future (I'm not doing any font work at the moment). If you want to convert any fonts or real testing, don't us fontsquirrel, it is literally terrible at this job. Use real tools like TTX and/or FontForge, or since the font is so small, literally just write the 30 or so bytes you need to turn a ttf/otf into an eot font manually, using a hex editor (which I'd probably recommend)

**Comment by dwighthouse** [comment]
It looks like your Minimal Font Generator might just meet my needs. Thanks for that! I will give it a try.

I have decided to eliminate WOFF2 and SVG Font support in tests.

* Only iOS 4.1 and lower support SVG fonts while not supporting other font formats. Global marketshare of these older iOS versions sits at 0%.
* WOFF2 support was removed as redundant, since any browser that supports WOFF2 also supports WOFF.

This leaves EOT for old IE, TTF for older browsers in general, and WOFF for modern browsers.

**Comment by Pomax** [comment]
Hm, are there any browsers that "supports TTF, does not support WOFF"? The only ones I can find are Firefox 3.5 and Chrome 4, neither of which are used anymore, Opera 10, which is also no longer used, Safari 5 and below, and IOS Safari 4.3 (both with really low usage); the only "real" browser I can think of for which ttf would be necessary is the Android webview engine, but its `ttf` support ever for Android 4.2 and 4.3 (it started supporting WOFF in 4.4) is *super* flaky.

I'd probably go with just WOFF and EOT, given how far back we need to go to find browsers that do TTF but not WOFF, but as an interesting idea: it is fairly easy to extract the original TTF from a WOFF in-browser by just slicing up the bytecode (provided the WOFF wasn't deflated of course) so that might be an interesting option.

**Comment by dwighthouse** [comment]
Well, these are just for tests, mind you. My library doesn't need any fonts of its own to operate. Any reduction in font usage for the tests is just to reduce the weight of the test code.

It is as you say, Android tends to have a longer tail. And I would have limited it to just EOT and TTF, except that IE (including mobile IE) has some specific requirements about it being an "installable font", which I can't necessarily guarantee. I simply don't have the skills or time to hand-edit hex files or read font format specs. All I really want to do is guarantee some test cases using test fonts known to have this or that property. My goal is not to be a font format expert.

**Comment by Pomax** [comment]
that's fair enough, having worked my way deep into the OpenType spec it's not a journey I recommend many people. That said, editing things becomes nearly infinitely easier with the TTX tool (part of [fonttools](https://github.com/fonttools/fonttools)), which lets you just throw a font at it, get super easy human-editable XML code back, change that stupid "permissions" bit to what it needs to be, and then throw the XML file back at TTX to convert it into a TTF (or OTF) again.

**Comment by dwighthouse** [comment]
Your minimal font tool unfortunately didn't work out very well, because it generated a TTF that couldn't be converted into a EOT that worked in IE. I ultimately had to use a FontSquirrel exported font, that I then edited with fonttools to get a space-less font that could then be correctly converted to an IE-compatible EOT file.

I've added tests for this unusual case in my test suite.

**Comment by Pomax** [comment]
Interesting... EOT is essentially just a wrapper around the original font, just like  WOFF-without-compression, so it might be that on ancient IE the TTF itself is overoptimised. Not sure if I'll ever get to it, but I've filed that as an issue on the repo. Thanks for the heads up.

**Comment by dwighthouse** [comment]
It could be something to do with the "installable" feature of TTF. I couldn't convert one of my earlier FontSquirrel fonts correctly, but when I unchecked the "WebOnly" feature, it worked.

**Comment by Pomax** [comment]
hm, pretty sure I generate the TTF with the installable bit set, but... let me check!

**Comment by dwighthouse** [comment]
Well, I'm out of ideas. On IE6, the font simply didn't load (apparently lacking a valid font is a silent failure in IE6).

**Comment by Pomax** [comment]
damn. I'll have to grab myself a modern.ie IE6 VM and investigate, probably won't have time for that until the weekend though.

**Comment by dwighthouse** [comment]
Actually, there's one other idea. I had left the entry for space but defined it as .notdef, rather than removing its entry in the cmap tables (I think). Convert the TTF to TTX I made: https://github.com/dwighthouse/onfontready/blob/2.0-SpaceCharacter/tests/mainTests/custom_fonts/f_F1.ttf

On IE6, the font simply didn't load (apparently lacking a valid font is a silent failure in IE6). Incidentally, the tool I used to convert the TTF to EOT (and also WOFF), is here: https://everythingfonts.com/ttf-to-eot

Notably, I tried about 4 different font conversion services, and all but one produce byte-identical conversions of your minimal TTF to EOT, so maybe they were all using the same underlying library.

**Comment by Pomax** [comment]
to be fair: the minimal font is spec-compliant, but *not* generic service compliant, so while it works in the browser, it will almost certainly fail conversion by online services. These services generally are much stricter about what a "legal" font is compared to what the spec *actually* says.

**Comment by dwighthouse** [comment]
Makes sense. Kinda like how there are hundreds of JPEG decoders, but not one of them actually implements the entire JPEG spec. Too complex, not worth it.

**Comment by Pomax** [comment]
yeah kind of, although also kind of in the opposite direction: the spec itself is actually really permissive in terms of what data you can omit and what data needs to be kept in, which in a bizar twist is actually more work to implement in a parser than to just say "well no NORMAL font would ever ... so let's just reject all fonts that do". It works, for the most part, until you hit that one, free, hand-crafted font that breaks your simplified model, or that $599 intricate Urdu font that gets the most out of OpenType =)

**Comment by dwighthouse** [comment]
Changes made with [1.1.0 release](https://github.com/dwighthouse/onfontready/pull/6)!
